filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
    
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log

processors:
- add_cloud_metadata: ~
- decode_json_fields:
     fields: ['message']
     target: nginx

output.elasticsearch:
  hosts: 'elasticsearch:9200'
  username: ''
  password: ''
setup.kibana:
  host: "kibana:5601"