version: '3.4'
services:
  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./out/access.log:/dev/stdout:rw
      - ./out/error.log:/dev/strerr:rw

  filebeat:
    container_name: filebeat
    image: "store/elastic/filebeat:7.2.0"
    networks: 
      - elk
    volumes: 
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./out/access.log:/var/log/nginx/access.log
      - ./out/error.log:/var/log/nginx/error.log:ro

  elasticsearch:
    container_name: elasticsearch
    image: "elasticsearch:7.2.0"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    environment: 
      - "discovery.type=single-node"
    networks: 
      - elk
      
  kibana:
    container_name: kibana
    image: "kibana:7.2.0"
    volumes:
      - elk
    ports:
      - "5601:5601"
    networks: 
      - elastic

  logstash:
    container_name: logstash
    image: "logstash:7.2.0"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    networks: 
      - elk
    ports:
      - "5044:5044"
      - "9600:9600"

  grafana:
    container_name: grafana
    image: "grafana/grafana"
    volumes: 
      - grafana
    ports:
      - "3000:3000"
    networks: 
      - elk

networks: 
  elk:

volumes: 
  elastic:
  kibana:
  grafana: